export type IFrames =
  | (typeof LoaderStyles)[keyof typeof LoaderStyles]
  | string[];

const BLOCK = ['▖', '▘', '▝', '▗'] as const;
const DOTS = ['⡀', '⠄', '⠂', '⠁', '⠈', '⠐', '⠠', '⢀'] as const;
const TRIANGLE = ['◢', '◣', '◤', '◥'] as const;
const CORNER_SQUARES = ['◰', '◳', '◲', '◱'] as const;
const ARROW = ['▸▹▹▹▹', '▹▸▹▹▹', '▹▹▸▹▹', '▹▹▹▸▹', '▹▹▹▹▸'] as const;
const BOUNCING_BAR = [
  '[    ]',
  '[=   ]',
  '[==  ]',
  '[=== ]',
  '[====]',
  '[ ===]',
  '[  ==]',
  '[   =]',
  '[    ]',
  '[    ]',
] as const;

const BLINK = [
  '(o)(o)',
  '(o)(o)',
  '(o)(o)',
  '(o)(o)',
  '(o)(o)',
  '(o)(o)',
  '(o)(o)',
  '(o)(o)',
  '(o)(o)',
  '(o)(o)',
  '(o)(o)',
  '(o)(o)',
  '(o)(o)',
  '(o)(o)',
  '(o)(o)',
  '(o)(o)',
  '(o)(o)',
  '(o)(o)',
  '(o)(o)',
  '(o)(o)',
  '(o)(o)',
  '(o)(o)',
  '(o)(o)',
  '(o)(o)',
  '(o)(o)',
  '(-)(-)',
  '(_)(_)',
  '(o)(o)',
  '(o)(o)',
  '(o)(o)',
  '(o)(o)',
  '(o)(o)',
  '(o)(o)',
  '(o)(o)',
  '(o)(o)',
  '(-)(-)',
  '(_)(_)',
  '(o)(o)',
  '(o)(o)',
  '(o)(o)',
  '(o)(o)',
  '(o)(o)',
  '(o)(o)',
  '(o)(o)',
  '(o)(o)',
  '(o)(o)',
  '(o)(o)',
  '(o)(o)',
  '(o)(o)',
  '(o)(o)',
  '(o)(o)',
  '(o)(o)',
  '(o)(o)',
  '(o)(o)',
  '(-)(-)',
  '(_)(_)',
] as const;
const FISH = [
  ">))'>     ",
  " >))'>    ",
  "  >))'>   ",
  "   >))'>  ",
  "    >))'> ",
  "     >))'>",
  "     <'((<",
  "    <'((< ",
  "   <'((<  ",
  "  <'((<   ",
  " <'((<    ",
  "<'((<     ",
] as const;

export const LoaderStyles = {
  BLOCK,
  DOTS,
  TRIANGLE,
  CORNER_SQUARES,
  ARROW,
  BOUNCING_BAR,
  BLINK,
  FISH,
};
